apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: ${YOUR_ACCESS_ID}
  secretAccessKey: ${YOUR_SECRET_KEY} 
# For AWS set it to "https://s3.<region>.amazonaws.com", for example https://s3.eu-central-1.amazonaws.com
  endpoint: "https://s3.ap-south-1.amazonaws.com"
  # For AWS set it to AWS region
  region: "ap-south-1"